<a href="https://colab.research.google.com/github/VenukaRao/Basics/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Basics

In [5]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape #n rows and m columns 

(3, 5)

In [7]:
a.ndim #number of axes of the array

2

In [8]:
a.dtype.name #one describing the type of elements in the array

'int64'

In [9]:
a.itemsize #the size in bytes of each element of the array

8

In [10]:
a.size #Total number of elements of the array 

15

In [11]:
type(a) # 

numpy.ndarray

In [12]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [13]:
type(b) 

numpy.ndarray

In [14]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b = np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [17]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
np.empty((2,3))

array([[2.35323467e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [25]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [26]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [27]:
from numpy import pi

In [28]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [31]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [32]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [35]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [36]:
a<35

array([ True,  True, False, False])

In [38]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

In [39]:
A * B

array([[2, 0],
       [0, 4]])

In [40]:
A @ B

array([[5, 4],
       [3, 4]])

In [41]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [42]:
rg = np.random.default_rng(1)
a = np.ones((2,3),dtype=int)
b = rg.random((2,3))

In [43]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [45]:
b += a
b

array([[6.51182162, 6.9504637 , 6.14415961],
       [6.94864945, 6.31183145, 6.42332645]])

In [46]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [48]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [49]:
c.dtype.name

'float64'

In [50]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [51]:
d.dtype.name

'complex128'

In [53]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [54]:
a.sum()

3.1057109529998157

In [55]:
a.min()

0.027559113243068367

In [56]:
a.max()

0.8277025938204418

In [57]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [59]:
b.min(axis=1)

array([0, 4, 8])

In [60]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [61]:
B = np.arange(3)
B

array([0, 1, 2])

In [63]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [64]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [65]:
C = np.array([2., -1., 4.])
np.add(B,C)

array([2., 0., 6.])

In [66]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [67]:
a[2]

8

In [68]:
a[2:5]

array([ 8, 27, 64])

In [71]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [72]:
a[::-1] 

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [73]:
for i in a:
  print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [74]:
def f(x,y):
  return 10 * x + y

In [75]:
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [76]:
b[2,3]

23

In [77]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [78]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [79]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [80]:
b[-1]

array([40, 41, 42, 43])

In [81]:
c = np.array([[[0,1,2],[10,12,13]],[[100,101,102],[110,112,113]]])
c.shape

(2, 2, 3)

In [82]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [83]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [84]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [85]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
